### PR TITLE
pythongen test: make pylint checks stricter

### LINKED ISSUE #111: pythongen: Make pylint checks stricter in the tests
The same way we ignore a set of warnings when running `pycodestyle`, we could ignore justifiable warnings with `pylint`, instead of running in errors-only mode. This way we can ensure that we do not introduce regressions and can gradually improve the code quality.

### PR DESCRIPTION
**Pull request by gaborigloi**
Instead of only checking for errors, now we have a whitelist of
warnings.

I had to rename TypeError to RpcTypeError to ensure it does not class
with the built-in exception with the same name. It does not seem to be
used by clients, SM raises the normal TypeError at a few places, but
that should be fine.

Warnings I did not remove:
* line-too-long,too-few-public-methods(for the exns),unused-argument(for
  the skeleton classes),no-self-use(for the skeletons, ...):
  it's pointless or impossible to remove these
* invalid-name: We cannot convert the classes to CamelCase without breaking the interface
* broad-except: it is necessary to catch all exceptions at some places
* protected-access: I did not want to make _dispatcher public for now

Fixes #111 

Signed-off-by: Gabor Igloi <gabor.igloi@citrix.com>

### CODE REVIEW

File: src/lib/pythongen.ml [hunk 1]
```diff
@@ -35,42 +45,55 @@ class Rpc_light_failure(Exception):
...
+    """
+    Custom argparse action for specifying dictionaries on the command line.
+    The syntax is <prog> --dict_name key1 value1 --dict_name key2 value2 ...
+    """
     def __call__(self, parser, namespace, values, option_string=None):
-        k = values[0]
-        v = values[1]
+        key = values[0]
+        value = values[1]
         if ((hasattr(namespace, self.dest) and
```
Comment (mseri) [inline src/lib/pythongen.ml]: You don't need the double parentheses here

Comment (gaborigloi) [reply src/lib/pythongen.ml]: Good spot, I also had to indent it
